server:
  servlet:
    context-path: /clover

spring:
  profiles:
    active: dev
  datasource:
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 20  # 最大连接数
      minimum-idle: 5  # 最小空闲连接数
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    lettuce:
      pool:
        max-active: 10  # 最大连接数
        max-idle: 8  # 最大空闲连接数
        min-idle: 0  # 最小空闲连接数
        max-wait: -1ms  # 最大阻塞等待时间
